version: "3.7"
services:
  web:
    container_name: web
    build:
      context: .docker/web
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - .docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - products-php
    networks:
      - default

  front:
    build:
      context: angular
    ports:
      - 4200:4200
    links:
      - web
      - gateway-nginx
    volumes:
      - ./angular:/usr/src/app

  gateway-nginx:
    container_name: gateway-nginx
    build:
      context: .docker/web
    ports:
      - 8888:80
    volumes:
      - ./gateway:/var/www/html
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
      - users
    networks:
      - default

  users:
    container_name: users
    build:
      context: users
    ports:
      - 8081:8081
    links:
      - dbuser
    environment:
      NODE_ENV: development
    volumes:
      - ./users:/var/www/html
    networks:
      - default
    restart: always

  dbuser:
    image: postgres:12
    env_file: users/.env
    ports:
      - 54323:5432
    volumes:
      - dbuser-data:/var/lib/postgresql/data
    networks:
      - default

#  gateway-app:
#    build:
#      context: gateway
#      args:
#        - WITH_XDEBUG=false
#    env_file: .env
#    volumes:
#      - ./gateway:/var/www/html
#      - .docker/php/php.ini:/usr/local/etc/php/conf.d/zzz-php.ini
#    links:
#      - db
#    networks:
#      - default

# html laravel folder
  products-php:
    container_name: products-php
    build:
      context: .docker/php
      args:
        - WITH_XDEBUG=true
    env_file: .env
    volumes:
      - .:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/zzz-php.ini
    links:
      - db
    ports:
    - 9000:9000
    networks:
      - default

#  laravel-redis:
#    image: redislabs/redisearch:latest
#    restart: always
#    ports:
#      - 6378:6379
#    links:
#      - db
#      - web
#    networks:
#      - default

  db:
    image: postgres:12
    env_file: .docker/db/.env
    ports:
      - 54321:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default

  dbtest:
    image: postgres:12
    env_file: .docker/db/.env.testing
    ports:
      - 54322:5432
    volumes:
      - db-data-testing:/var/lib/postgresql/data
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:4.27
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@toto.com
      PGADMIN_DEFAULT_PASSWORD: toto
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "9998:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"    
      - "dbuser:pgsql-users-server"
      - "dbtest:test-pgsql-server"
    networks:
      - default

volumes:
  db-data:
  dbuser-data:
  db-data-testing:
  pgadmin-data:

networks:
  default:
    driver: bridge